name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write # for OIDC
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install packages
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.5.1
        with:
          version: npm run changeset version
          publish: npm run release
          title: 'chore: release x.y.z'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          createGithubReleases: false
