name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run test
        run: npm run test:cov

      - name: Check file changes
        run: |
          npm run build
          npx prettier --version
          npx prettier --check . || exit 100
          git status --short
          git diff
          git diff --quiet

      - name: Coveralls
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
